In [1]:
from garage.envs import GymEnv
import gym
import numpy as np

2023-06-12 15:12:11.330010: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /opt/ros/noetic/lib::/home/kh-ryu/.mujoco/mujoco200/bin
2023-06-12 15:12:11.330028: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.


In [2]:
# env = gym.make('CartPole-v1')
student_env = GymEnv('SparseHalfCheetahLimited-v2')

/home/kh-ryu/anaconda3/envs/surprise/lib/python3.8/site-packages/gym/spaces/box.py:73: UserWarning: WARN: Box bound precision lowered by casting to float32
  logger.warn(


In [3]:
student_env.action_space

Box([-0.8 -0.8 -0.8 -0.8 -0.8 -0.8], [0.8 0.8 0.8 0.8 0.8 0.8], (6,), float32)

In [5]:
student_env.seed(0)

[0]

In [6]:
student_env.reset()

(array([ 0.09307819,  0.02653819, -0.04199653, -0.07950315,  0.03461527,
        -0.02148465,  0.03396921, -0.08803221, -0.0572751 ,  0.00336234,
        -0.00317337,  0.04092179,  0.05138554,  0.01490225, -0.04298223,
         0.18408469, -0.00426755]),
 {})

In [7]:
result = student_env.step([1.0, 1.0, 1.0, 1.0, 1.0, 1.0])
result.observation

array([ 0.06325024, -0.05809922,  0.17893613,  0.21352236,  0.27692149,
        0.25006369,  0.20446423,  0.14140779,  1.04049294, -0.98866255,
       -2.35847982,  7.1019102 ,  7.24173569,  6.31255845,  7.38003616,
        5.02561432,  6.63598017])

In [8]:
student_env.seed(0)

[0]

In [9]:
student_env.reset()

(array([ 0.09307819,  0.02653819, -0.04199653, -0.07950315,  0.03461527,
        -0.02148465,  0.03396921, -0.08803221, -0.0572751 ,  0.00336234,
        -0.00317337,  0.04092179,  0.05138554,  0.01490225, -0.04298223,
         0.18408469, -0.00426755]),
 {})

In [10]:
result = student_env.step([0.8, 0.8, 0.8, 0.8, 0.8, 0.8])
result.observation

array([ 0.06325024, -0.05809922,  0.17893613,  0.21352236,  0.27692149,
        0.25006369,  0.20446423,  0.14140779,  1.04049294, -0.98866255,
       -2.35847982,  7.1019102 ,  7.24173569,  6.31255845,  7.38003616,
        5.02561432,  6.63598017])

In [ ]:
env.action_space